import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AosInit from "@/components/layouts/AosInit";
import { cn } from "@/lib/utils";
import Navbar from "@/components/layouts/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "GreenHouse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", poppins.variable, "font-sans")}
    >
      <body className="min-h-full flex flex-col">
        <AosInit />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
